version: "3"

services:

    db:
        build: 
            context: ./postgres
            dockerfile: Dockerfile 
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
           - 5432:5432
        networks:
            - db_nw
            
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf    # Hostfolder:Containerfolder
        ports:
            - 5000:80   # Host port:Container port
        depends_on:
            - flask
        networks:
            - web_nw
         
    flask:
        build: 
            context: ./flask
            dockerfile: Dockerfile
        volumes:
            - ./flask:/usr/src/app
        networks:
            - db_nw
            - web_nw
            
networks:
    db_nw:
    # Containers connected to the same user-defined bridge network automatically
    #expose all ports to each other, and no ports to the outside world.
        driver: bridge
    web_nw:
        driver: bridge
        
volumes:
    db_data: