name: Docker Image CI

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: Build the stack
        run: docker-compose up -d
      - name: Check logs
        run: docker logs backend
      - name: See running containers 
        run: docker ps 
